# Generated by Django 4.2.2 on 2023-06-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Format: dd/mm/yyyy hh:mm', verbose_name='Post Date'),
        ),
    ]
